project_id = "zqohnagvnvpczduoizdh"

[functions.stripe-connect-oauth-callback]
verify_jwt = false

[functions.create-invoice-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
