project_id = "zqohnagvnvpczduoizdh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-price-suggestion]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.quote-response]
verify_jwt = false

[functions.generate-job-occurrences]
verify_jwt = false

[functions.extend-horizon]
verify_jwt = false

[functions.calendar-unified]
verify_jwt = false

[functions.regenerate-occurrences]
verify_jwt = false

# Scheduled job to extend horizons daily - DISABLED for security
# [[db.functions]]
# name = "extend_horizon_scheduler"
# sql = """
# -- Disabled due to hardcoded API key security concern
# -- Should be reimplemented with proper environment variable handling
# """

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"